/**
 * Fixtures
 */

export namespace types {
  // String Literal Types
  export const VERY_DEEP_WITH_TYPE_ONLY = 'VERY_DEEP_WITH_TYPE_ONLY';
  export const WITH_TYPE_ONLY = 'WITH_TYPE_ONLY';
  export const WITH_PAYLOAD = 'WITH_PAYLOAD';
  export const WITH_OPTIONAL_PAYLOAD = 'WITH_OPTIONAL_PAYLOAD';
  export const WITH_META = 'WITH_META';
  export const WITH_PAYLOAD_META = 'WITH_PAYLOAD_META';
  export const WITH_MAPPED_PAYLOAD = 'WITH_MAPPED_PAYLOAD';
  export const WITH_MAPPED_META = 'WITH_MAPPED_META';
  export const WITH_MAPPED_PAYLOAD_META = 'WITH_MAPPED_PAYLOAD_META';
  export const SIMPLE_WITH_TYPE_ONLY = 'SIMPLE_WITH_TYPE_ONLY';
  export const SIMPLE_WITH_PAYLOAD = 'SIMPLE_WITH_PAYLOAD';
  export const SIMPLE_WITH_OPTIONAL_PAYLOAD = 'SIMPLE_WITH_OPTIONAL_PAYLOAD';
  export const SIMPLE_WITH_META = 'SIMPLE_WITH_META';
  export const SIMPLE_WITH_PAYLOAD_META = 'SIMPLE_WITH_PAYLOAD_META';
}
